name       : haskell-http-types
version    : 0.9.1
release    : 1
source     :
    - http://hackage.haskell.org/package/http-types-0.9.1/http-types-0.9.1.tar.gz : 7bed648cdc1c69e76bf039763dbe1074b55fd2704911dd0cb6b7dfebf1b6f550
license    : BSD-3-Clause
component  : programming.haskell
summary    : Generic HTTP types for Haskell (for both client and server code). 
description: |
    Generic HTTP types for Haskell (for both client and server code). 
builddeps  :
    - haskell-blaze-builder
    - haskell-cabal-install
    - haskell-case-insensitive
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
