name       : haskell-http-types
version    : 0.12.1
release    : 2
source     :
    - https://hackage.haskell.org/package/http-types-0.12.1/http-types-0.12.1.tar.gz : 3fa7715428f375b6aa4998ef17822871d7bfe1b55ebd9329efbacd4dad9969f3
license    : BSD-3-Clause
component  : programming.haskell
summary    : Generic HTTP types for Haskell (for both client and server code).
description: "Generic HTTP types for Haskell (for both client and server code). \n"
builddeps  :
    - haskell-blaze-builder
    - haskell-cabal-install
    - haskell-case-insensitive
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
