name       : haskell-http-types
version    : 0.12.3
release    : 3
source     :
    - https://hackage.haskell.org/package/http-types-0.12.3/http-types-0.12.3.tar.gz : 4e8a4a66477459fa436a331c75e46857ec8026283df984d54f90576cd3024016
license    : BSD-3-Clause
component  : programming.haskell
summary    : Generic HTTP types for Haskell (for both client and server code).
description: |
    Generic HTTP types for Haskell (for both client and server code).
builddeps  :
    - haskell-cabal-install
    - haskell-case-insensitive-devel
rundeps    :
    - devel:
        - haskell-case-insensitive-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
